server:
  port: 8082
spring:
  application:
    name: configclient
  cloud:
    config:
      uri: "http://localhost:8080"
      profile: test
      label: main
      name: configclient
      enabled: false
  config:
    activate:
      on-profile: test